# Generated by Django 3.0.8 on 2021-02-06 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20210206_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='post_image',
        ),
        migrations.AddField(
            model_name='post',
            name='post_document',
            field=models.FileField(blank=True, default='post.png', null=True, upload_to='Post_documents'),
        ),
    ]
