# Generated by Django 3.0.8 on 2021-03-13 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_profile_is_online'),
        ('posts', '0008_all_post_thought'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thought',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
