# Generated by Django 3.0.8 on 2021-03-01 17:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_profile_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob_date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
