# Generated by Django 3.0.8 on 2021-03-02 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_profile_dob_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='dob_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
